Completed task-8
Martin-Abbott/MA-FE-NC-GAMES pull request #6
Opened 2023-06-01 15:28 UTC by Martin-Abbott

2023-06-01 15:51 UTC, HannahBurks reviewed
If I click post multiple times to post a comment, the page goes black and crashes. Look how you can prevent multiple clicks and stop the button from being clicked whilst the post goes through.

2023-06-01 15:53 UTC, HannahBurks reviewed
If I click post multiple times to post a comment, the page goes black and crashes. Look how you can prevent multiple clicks and stop the button from being clicked whilst the post goes through.

2023-06-01 15:53 UTC, HannahBurks commented on MA-FE-NC-GAMES/components/CommentAdder.jsx
> +			<form onSubmit={handleSubmit}>
We want to add some form validation here to prevent us being able to post an empty comment :)

2023-06-01 15:55 UTC, HannahBurks requested changes
Nice start Martin but some form related errors to be handled. We also need to ensure we don't post multiple of the same comment . Once implemented please send another PR tomorrow :) nice work today!

2023-06-02 09:58 UTC, aloush-dev approved these changes
nice job merge away

2023-06-02 09:59 UTC, merged